### PR TITLE
Adding yaml config option for Redis params and ttl

### PR DESCRIPTION
**Pull request by NicholasArvin**
## Description

Adding yaml config option for Redis params and ttl

## Related Issues

https://github.com/dm4ml/motion/issues/143

## Checklist

Please make sure that you have completed the following items before submitting this pull request:

- [ ] Code is up-to-date with the main branch
- [ ] Code has been tested locally and all tests pass
- [ ] Code changes have been documented (if necessary)
- [ ] Code changes adhere to the project's coding standards
- [ ] Any necessary new dependencies have been added to the project's `pyproject.toml` file

## Additional Notes

This passes the unit tests in the makefile. I wasn't totally sure how to test this (e.g. what to set the Redis params to), so let me know if I should write custom tests.

### CODE REVIEW

**Review by shreyashankar — CHANGES_REQUESTED** [review]
This is great! Small nit: Can you add `types-pyyaml` to dev dependencies instead of main dependencies? You'll probably want to do something like this:

```bash
poetry remove types-pyyaml
poetry add -D types-pyyaml
```

**Review by shreyashankar — CHANGES_REQUESTED** [review]
Re: meeting today:

* load the yaml once, in the instance or executor, and pass in the config dict to the RedisParams constructor instead of loading the yaml every time a new RedisParams object is created

**Comment by NicholasArvin** [comment]
I moved the yaml loading to just the constructor of the executor. I modified the test in conftest.py to include the yaml option. 
I had difficulty with merging and rebasing, so let me know if something's not right.

**Review by shreyashankar — APPROVED** [review]
LGTM

**Pull request merged**
